ersion: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
    commands:
# This isn't necessary at the moment, but sometimes the build images fall behind current version of the AWS CLI
#      - pip install --upgrade awscli
      - pip install --user aws-sam-cli
      - USER_BASE_PATH=$(python -m site --user-base)
      - export PATH=$PATH:$USER_BASE_PATH/bin 
  pre_build:
    commands:
      - echo "Creating Maven Jar File"
  build:
      - echo Build started on `date`
      - aws cloudformation package --debug --template-file template.yml --s3-bucket hemantsambucket --output-template-file packaged-template.yml
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/DemoJava-0.0.1-SNAPSHOT.jar
    - packaged-template.yml
  discard-paths: yes
