AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: chapter5-data-pipeline

Globals:
 Function:
    Runtime: java8
    MemorySize: 512
    Timeout: 10
    Environment:
      Variables:
        TABLE_NAME: data-table 
        weeklyupdate: Friday
        clientid: ce5b2c39d7681153b059b561083f788328fec076a001df62fc41a9d3eef5a6fe
        clientsecret: 06127a29ea2dfd1e32fc2b0ba44aacdaf0978c77691e7f00d97bd3172a9408cc
        urlPrefix: jdbc:db2
        database: udbprod
        host: pbudwprod
        port: 7450
        dbUser: idmgtdb2
        dbPassword: 35g8EdSH     
Resources:
 PipelineStartBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}-start
 
 FanOutTopic:
   Type: AWS::SNS::Topic

 BulkEventsLambda:
  Type: AWS::Serverless::Function
  Properties:
      CodeUri: target/DemoJava-0.0.1-SNAPSHOT.jar
      Handler: demo.test::handler
      Environment:
       Variables:
         FAN_OUT_TOPIC: !Ref FanOutTopic
       VpcConfig:
         SecurityGroupIds:
          - sg-040ed53e
         SubnetIds:
          - subnet-4305a61c
          - subnet-6332432e    
      Policies:
      - S3ReadPolicy:
          BucketName: !Sub ${AWS::StackName}-${AWS::AccountId}-${AWS::Region}-start
      - SNSPublishMessagePolicy:
          TopicName: !GetAtt FanOutTopic.TopicName
      Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: !Ref PipelineStartBucket
            Events: s3:ObjectCreated:*
